### ISSUE TITLE
TODO's for Android O

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra-android#151]
- [x] Explore using Lifecycle Components (done, see architecture branch)
- [x] Make app compatible with android O
  * [x] Update notifications to use channels
  * [x] Check and maybe update account-related stuff
- [ ] Provide adaptive icon (#164)
- [ ] Fix Urgent.fm music service (#163)

**Comment by niknetniko** [comment]
I've extracted the remaining bullet points to separate issues.
