### ISSUE TITLE
Codenight 16/10

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/hydra-android#209]
Yowkes

Wonder how to get rolling in this codenight? Be sure to read [this #TODO]() blogpost.
If you're ready, take a look at the issues below, we selected a couple that are easy to fix for somebody new to the project.
If you need any help or have any questions, be sure to ask @wschella, @niknetniko or @feliciaan.

A [filtered overview](https://github.com/ZeusWPI/hydra-android/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aeasy) of all relevant issues.

Handpicked for you:
- [x] #208 Make resto items copyable
- [x] #207 Add accent color to Schamper articles
- [x] #206 Don't display an empty lead in Schamper articles
- [x] #205 Make location clickable in events
- [ ] #204 Add some social media links for Urgent.fm
- [x] #189 Add legend to resto tab

These are mostly small visuals changes to get you familiar with the codebase, if you feel you need some structural changes in the logic, contact one of the devs.

Happy coding!

**Comment by niknetniko** [comment]
The codenight has been completed. Thanks to everyone who was there!

**Comment by wschella** [comment]
Great work peeps
