### ISSUE TITLE
Complete daily notifications

### ISSUE THREAD

**Issue by R13N** [ZeusWPI/hydra-android#29]
### Todo in the [daily-notifications](https://github.com/ZeusWPI/hydra-android/tree/daily-notifications)-branch:
- [x] Listen to weekdays
- [x] Look for other `TimePicker` which has 24h support
- [ ] Better logo for notifications
- [x] Go directly to the `RestoActivity` when the notification is clicked
- [ ] Option to warn the user when the resto is closed
- [ ] Show the actual menu in the notification (Reuse `RestoCard`?)

**Comment by niknetniko** [comment]
Plz fix nao @R13N

**Comment by niknetniko** [comment]
Y no fixt jet @R13N

**Comment by feliciaan** [comment]
Srs @R13N

**Comment by niknetniko** [comment]
@R13N u neet to fx noa

**Comment by niknetniko** [comment]
plz, im waitin on tis @R13N

**Comment by niknetniko** [comment]
This feature was removed in the latest beta, in part due to a lack of maintenance. See commit 96077dceba9f87c4c5871e774b223cb8e71d3baa.
